### ISSUE TITLE
Fixing some issues on special characters in names an non latin1 characters in names and values

### ISSUE THREAD

**Issue by vboehm** [Quiq/influxdb-tools#10]
When trying to save and restore the `InfluxDB` data for my `HomeAssistant` instance I ran into some errors:

*   **It is impossible to save measurements containing a slash ('/') like 'm/s', 'l/h' or 'm³/d'.**  
    You can replace the slash in the filename by another charachter (U+2044 FRACTION SLASH,  
    U+2215 DIVISION SLASH, U+2571 is BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT etc.) 
    or a sequence of characters ('&lt;@&gt;', '=>' or what you like).  
    I preferred the U+2571 solution and fixed it in this way.
*   **Identifiers (measurements, tag keys and field keys) containing some characters are not stored correctly**  
    Since it is allowed to use Blank (' '), comma (',') and equal sign ('=') in tag keys and field keys
    and blanks and commas in measurements (see [InfluxDB documentation](https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/)),
    these characters must also be escaped. Until now (commit #166779d) only values are escaped.  
    I fixed this also.
*   **Measurements, tag keys, fields keys or values containing non-latin1 characters cannot be restored**
    When restoring files containing characters which are not included in the `latin1` character set,
    the build of the write request failed. When the `data` parameter to `requests.post()` is a string
    it will be converted to the standard HTTP character set `latin1` which fails for non-latin1 characters.  
    When this parameter is of type `bytes` no conversion takes place and everything works fine.  
    This issue is also fixed.

The 1st and 3rd flaw were already mentioned in the issues #3 and #6.

I hope these changes make this nice program a little bit more usable :-)

Volker Böhm (volker@vboehm.de)

P.S.: I have a working copy of the changes in my git repository but I don't know how to put it into a pull request on GitHub.

I attached the updated file `influx-backup.py` as `influx-backup.txt` since the bloody `GitHub` does not accept PY-files :-(
[influx-backup .txt](https://github.com/Quiq/influxdb-tools/files/9485106/influx-backup.txt)

**Comment by roman-vynar** [comment]
Many thanks!

I have also amended this line
```
                     else:
                         if type(val) == str:
-                            val = val.replace(' ', '\ ').replace(',', '\,').replace('=', '\=')
+                            val = identifier2lineprotocol(val)
```

**Comment by roman-vynar** [comment]
https://github.com/Quiq/influxdb-tools/commit/3789263524dd9cd23a78203e4957c932c93c8b6f
