### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by asarubbo** [Quiq/influxdb-tools#5]
I'm running the latest influx-backup.py from an up-to-date debian9.

The influxdb version is 0.12 on centos6:
The access is allowed without user/pass

```python3 influx-backup.py --url http://IP:8086 --user "" --dump --dump-db data --dir backup/```

I get:
```Password: 
>> 2019-02-06 16:00:59 UTC
Starting backup of "data" db to "backup/" dir 

Measurements:
['TABLES]

Traceback (most recent call last):
  File "influx-backup.py", line 319, in <module>
    dump(args.dump_db, WHERE)
  File "influx-backup.py", line 128, in dump
    msfields[i['series'][0]['name']] = {x[0]: x[1] for x in i['series'][0]['values']}
  File "influx-backup.py", line 128, in <dictcomp>
    msfields[i['series'][0]['name']] = {x[0]: x[1] for x in i['series'][0]['values']}
IndexError: list index out of range```

**Comment by roman-vynar** [comment]
influxdb 0.12 is very old one and not sure if it ever works there.

**Comment by asarubbo** [comment]
If you are not sure that it works with the very old, I'd suggest to add a check against the version of the server before do something
