### ISSUE TITLE
Restore fails with UnicodeError

### ISSUE THREAD

**Issue by jirisembera** [Quiq/influxdb-tools#6]
In case the dump contains non-ASCII characters data restore fails. Encoding the payload to UTF-8 before passing it to requests solves the problem:

`r = requests.post(URL+'/write', auth=AUTH, params=params, data=data.encode("UTF-8"))`

**Comment by roman-vynar** [comment]
Fixed by https://github.com/Quiq/influxdb-tools/commit/3789263524dd9cd23a78203e4957c932c93c8b6f
