### ISSUE TITLE
Invalid line protocol when no tag in source measurements

### ISSUE THREAD

**Issue by aimakun** [Quiq/influxdb-tools#7]
I found parse data failed during restore data from backup and realized that because the source measurements didn't have any tag.

Add a tag length check before backup data point could fix this issue:
```python
if len(tags) == 0:
    rows.append(f"{m} {','.join(fields)} {timestamp}\n")
else:
    rows.append(f"{m},{','.join(tags)} {','.join(fields)} {timestamp}\n")
```

**Comment by roman-vynar** [comment]
Thanks!

Can you send a PR?
