### ISSUE TITLE
Entity too large error while restoring the DB

### ISSUE THREAD

**Issue by aggvinay** [Quiq/influxdb-tools#9]
While trying to restore DB with file around 5 MB it is producing following error:

```
Loading stats...  413 HTTP error, <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.15.6</center>
</body>
</html>
```

**Comment by roman-vynar** [comment]
This is neither influxdb nor script problem.

According to your error it's your nginx limits, post_max_size or something.

**Comment by aggvinay** [comment]
Thanks,
I got it resolved by reducing the default WRITE_CHUNK_SIZE in script from 5000 to 1000
